import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";
import { readManifest } from "./lockfile";

const GATEWAY_CONTAINER = "podokit-dev-gateway";
const GATEWAY_IMAGE = "traefik:v3.5";
const GATEWAY_LABEL = "io.podosoft.podokit.dev-gateway";
const GATEWAY_NETWORK = "podokit-dev-gateway";
const RUNTIME_COMPOSE = ".podokit/runtime/dev.compose.yaml";
const DEV_CONFIG = ".podokit/dev.json";

export interface DevConfig {
  schemaVersion: 1;
  hostname: string;
  publicUrl?: string;
}

export interface DevRuntime {
  alias: string;
  config: DevConfig;
  projectRoot: string;
  routeId: string;
  runtimeComposePath: string;
}

interface CommandResult {
  status: number | null;
  stdout: string;
  stderr: string;
}

export type CommandRunner = (
  command: string,
  args: string[],
  options: { capture: boolean },
) => CommandResult;

function defaultRunner(
  command: string,
  args: string[],
  options: { capture: boolean },
): CommandResult {
  const result = spawnSync(command, args, {
    encoding: "utf8",
    stdio: options.capture ? "pipe" : "inherit",
  });
  if (result.error) throw result.error;
  return {
    status: result.status,
    stdout: options.capture ? (result.stdout ?? "") : "",
    stderr: options.capture ? (result.stderr ?? "") : "",
  };
}

function parseJson<T>(path: string): T {
  try {
    return JSON.parse(readFileSync(path, "utf8")) as T;
  } catch (error) {
    throw new Error(`Cannot read ${path}: ${(error as Error).message}`);
  }
}

function validateHostname(hostname: string): void {
  if (
    hostname.length > 253 ||
    !hostname.endsWith(".localhost") ||
    !/^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?\.localhost$/.test(hostname)
  ) {
    throw new Error(
      `Invalid development hostname "${hostname}". Use a lowercase *.localhost hostname without a scheme or port.`,
    );
  }
}

function validatePublicUrl(publicUrl: string): void {
  let parsed: URL;
  try {
    parsed = new URL(publicUrl);
  } catch {
    throw new Error(`Invalid publicUrl "${publicUrl}". Use an absolute HTTPS URL.`);
  }
  if (parsed.protocol !== "https:" || parsed.pathname !== "/" || parsed.search || parsed.hash) {
    throw new Error(`Invalid publicUrl "${publicUrl}". Use an HTTPS origin without a path.`);
  }
}

export function readDevConfig(projectRoot: string): DevConfig {
  const path = join(projectRoot, DEV_CONFIG);
  const manifest = readManifest(projectRoot);
  if (!manifest) throw new Error("Not a PodoKit project: .podokit/manifest.json is missing.");

  const fallbackName = manifest.answers.projectName;
  if (!fallbackName) throw new Error("PodoKit manifest is missing answers.projectName.");
  const config = existsSync(path)
    ? parseJson<DevConfig>(path)
    : { schemaVersion: 1 as const, hostname: `${fallbackName}.localhost` };

  if (config.schemaVersion !== 1) {
    throw new Error(`Unsupported ${DEV_CONFIG} schemaVersion: ${String(config.schemaVersion)}`);
  }
  validateHostname(config.hostname);
  if (config.publicUrl) validatePublicUrl(config.publicUrl);
  return config;
}

function stableId(projectRoot: string): string {
  return createHash("sha256").update(projectRoot).digest("hex").slice(0, 10);
}

function slug(value: string): string {
  const normalized = value.toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "");
  return normalized.slice(0, 36) || "app";
}

export function resolveDevRuntime(projectRoot: string): DevRuntime {
  const root = resolve(projectRoot);
  const config = readDevConfig(root);
  const id = stableId(root);
  const projectSlug = slug(config.hostname.replace(/\.localhost$/, ""));
  return {
    alias: `podokit-${projectSlug}-${id}`,
    config,
    projectRoot: root,
    routeId: `route-${projectSlug}-${id}`,
    runtimeComposePath: join(root, RUNTIME_COMPOSE),
  };
}

export function renderRuntimeCompose(runtime: DevRuntime): string {
  return `# Generated by podo dev. Do not edit.\nservices:\n  traefik:\n    profiles: [podokit-legacy-proxy]\n  web:\n    networks:\n      ${GATEWAY_NETWORK}:\n        aliases: [${runtime.alias}]\nnetworks:\n  ${GATEWAY_NETWORK}:\n    external: true\n    name: ${GATEWAY_NETWORK}\n`;
}

export function renderRoute(runtime: DevRuntime): string {
  const { alias, config, routeId } = runtime;
  return `http:\n  routers:\n    ${routeId}:\n      entryPoints: [web]\n      rule: Host(\`${config.hostname}\`)\n      service: ${routeId}\n      middlewares: [${routeId}-compression]\n  services:\n    ${routeId}:\n      loadBalancer:\n        servers:\n          - url: http://${alias}:5001\n  middlewares:\n    ${routeId}-compression:\n      compress: {}\n`;
}

function devHome(): string {
  return process.env.PODOKIT_DEV_HOME ?? join(homedir(), ".podokit", "dev-gateway");
}

function registryDirectory(): string {
  return join(devHome(), "projects");
}

function routesDirectory(): string {
  return join(devHome(), "routes");
}

function registryPath(runtime: DevRuntime): string {
  return join(registryDirectory(), `${runtime.routeId}.json`);
}

function routePath(runtime: DevRuntime): string {
  return join(routesDirectory(), `${runtime.routeId}.yml`);
}

interface RegistryEntry {
  hostname: string;
  projectRoot: string;
  routeId: string;
}

function activeEntries(): RegistryEntry[] {
  const dir = registryDirectory();
  if (!existsSync(dir)) return [];
  const entries: RegistryEntry[] = [];
  for (const name of readdirSync(dir).filter((entry) => entry.endsWith(".json"))) {
    const path = join(dir, name);
    const entry = parseJson<RegistryEntry>(path);
    if (!existsSync(entry.projectRoot)) {
      rmSync(path, { force: true });
      rmSync(join(routesDirectory(), `${entry.routeId}.yml`), { force: true });
      continue;
    }
    entries.push(entry);
  }
  return entries;
}

function writeRuntimeFiles(runtime: DevRuntime): void {
  mkdirSync(join(runtime.projectRoot, ".podokit", "runtime"), { recursive: true });
  writeFileSync(runtime.runtimeComposePath, renderRuntimeCompose(runtime));
}

function registerRoute(runtime: DevRuntime): void {
  const collision = activeEntries().find(
    (entry) => entry.hostname === runtime.config.hostname && entry.projectRoot !== runtime.projectRoot,
  );
  if (collision) {
    throw new Error(
      `Development hostname ${runtime.config.hostname} is already registered by ${collision.projectRoot}. Change .podokit/dev.json or run podo dev down there.`,
    );
  }
  mkdirSync(registryDirectory(), { recursive: true });
  mkdirSync(routesDirectory(), { recursive: true });
  writeFileSync(routePath(runtime), renderRoute(runtime));
  const entry: RegistryEntry = {
    hostname: runtime.config.hostname,
    projectRoot: runtime.projectRoot,
    routeId: runtime.routeId,
  };
  writeFileSync(registryPath(runtime), `${JSON.stringify(entry, null, 2)}\n`);
}

function unregisterRoute(runtime: DevRuntime): void {
  rmSync(registryPath(runtime), { force: true });
  rmSync(routePath(runtime), { force: true });
}

function commandSucceeded(result: CommandResult): boolean {
  return result.status === 0;
}

function ensureDocker(runner: CommandRunner): void {
  const result = runner("docker", ["info", "--format", "{{.ServerVersion}}"], { capture: true });
  if (!commandSucceeded(result)) {
    throw new Error(`Docker is not available. ${result.stderr.trim()}`.trim());
  }
}

function ensureNetwork(runner: CommandRunner): void {
  const inspect = runner("docker", ["network", "inspect", GATEWAY_NETWORK], { capture: true });
  if (commandSucceeded(inspect)) return;
  const create = runner("docker", ["network", "create", GATEWAY_NETWORK], { capture: true });
  if (!commandSucceeded(create)) {
    throw new Error(`Cannot create Docker network ${GATEWAY_NETWORK}: ${create.stderr.trim()}`);
  }
}

function ensureGateway(runner: CommandRunner): void {
  const inspect = runner(
    "docker",
    ["inspect", "--format", `{{ index .Config.Labels \"${GATEWAY_LABEL}\" }} {{.State.Running}}`, GATEWAY_CONTAINER],
    { capture: true },
  );
  if (commandSucceeded(inspect)) {
    const [label, running] = inspect.stdout.trim().split(/\s+/);
    if (label !== "1") {
      throw new Error(`Container ${GATEWAY_CONTAINER} exists but is not managed by PodoKit.`);
    }
    if (running !== "true") {
      const start = runner("docker", ["start", GATEWAY_CONTAINER], { capture: true });
      if (!commandSucceeded(start)) {
        throw new Error(`Cannot start ${GATEWAY_CONTAINER}: ${start.stderr.trim()}`);
      }
    }
    return;
  }

  mkdirSync(routesDirectory(), { recursive: true });
  const run = runner(
    "docker",
    [
      "run",
      "--detach",
      "--name",
      GATEWAY_CONTAINER,
      "--label",
      `${GATEWAY_LABEL}=1`,
      "--restart",
      "unless-stopped",
      "--network",
      GATEWAY_NETWORK,
      "--publish",
      "127.0.0.1:80:80",
      "--volume",
      `${routesDirectory()}:/etc/traefik/dynamic:ro`,
      GATEWAY_IMAGE,
      "--providers.file.directory=/etc/traefik/dynamic",
      "--providers.file.watch=true",
      "--entrypoints.web.address=:80",
      "--api.dashboard=false",
    ],
    { capture: true },
  );
  if (!commandSucceeded(run)) {
    throw new Error(
      `Cannot start the shared PodoKit gateway on 127.0.0.1:80. Stop the current port owner, then retry. ${run.stderr.trim()}`.trim(),
    );
  }
}

function composeArgs(runtime: DevRuntime, args: string[]): string[] {
  return ["compose", "-f", "compose.dev.yaml", "-f", runtime.runtimeComposePath, ...args];
}

function runCompose(runtime: DevRuntime, args: string[], runner: CommandRunner): void {
  const result = runner("docker", composeArgs(runtime, args), { capture: false });
  if (!commandSucceeded(result)) {
    throw new Error(`docker compose ${args.join(" ")} exited with status ${String(result.status)}.`);
  }
}

function composeCommand(action: "down" | "exec" | "logs" | "ps" | "watch", args: string[]): string[] {
  const global: string[] = [];
  const command: string[] = [];
  for (let index = 0; index < args.length; index += 1) {
    const value = args[index];
    if (value === undefined) continue;
    if (value === "--profile") {
      const profile = args[index + 1];
      if (!profile) throw new Error("--profile requires a value.");
      global.push(value, profile);
      index += 1;
    } else if (value.startsWith("--profile=")) {
      global.push(value);
    } else {
      command.push(value);
    }
  }
  return [...global, action, ...command];
}

function stopGatewayWhenUnused(runner: CommandRunner): void {
  if (activeEntries().length > 0) return;
  runner("docker", ["rm", "--force", GATEWAY_CONTAINER], { capture: true });
  runner("docker", ["network", "rm", GATEWAY_NETWORK], { capture: true });
}

export function runDevCommand(
  projectRoot: string,
  action: string | undefined,
  args: string[],
  runner: CommandRunner = defaultRunner,
): void {
  const runtime = resolveDevRuntime(projectRoot);
  writeRuntimeFiles(runtime);

  if (action === "url") {
    process.stdout.write(`http://${runtime.config.hostname}\n`);
    if (runtime.config.publicUrl) process.stdout.write(`${runtime.config.publicUrl}\n`);
    return;
  }

  ensureDocker(runner);
  if (action === "watch") {
    ensureNetwork(runner);
    registerRoute(runtime);
    try {
      ensureGateway(runner);
      process.stdout.write(`Development URL: http://${runtime.config.hostname}\n`);
      if (runtime.config.publicUrl) process.stdout.write(`Public OAuth URL: ${runtime.config.publicUrl}\n`);
      runCompose(runtime, composeCommand("watch", args), runner);
    } catch (error) {
      unregisterRoute(runtime);
      stopGatewayWhenUnused(runner);
      throw error;
    }
    return;
  }

  if (action === "down") {
    runCompose(runtime, composeCommand("down", args), runner);
    unregisterRoute(runtime);
    stopGatewayWhenUnused(runner);
    return;
  }

  if (action === "exec" || action === "logs" || action === "ps") {
    runCompose(runtime, composeCommand(action, args), runner);
    return;
  }

  throw new Error("Usage: podo dev <watch|exec|logs|ps|down|url> [docker compose options]");
}
