apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: podokit
data:
  NODE_ENV: "production"
  PORT: "3000"
  CORS_ORIGIN: "https://example.com"
  BACKEND_INTERNAL_URL: "http://api:3000"
